/*
 * This source file was generated by the Gradle 'init' task
 */
package org.authservice;

import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    public static void main(String[] args) {
        org.springframework.boot.SpringApplication.run(App.class, args);
    }
}

